election/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired






class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    content = TextAreaField('Content' , validators=[DataRequired()])
    submit = SubmitField('Post')

election/main/routes.py
from flask import Blueprint , render_template, request
from election.models import Post


main = Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    # page =request.args.get('page', 1 , type=int)
    # posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=6)
    return render_template('home.html')

@main.route("/not_done")
def not_done():
    return render_template('not_done.html')



@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/community")
def community():
    page =request.args.get('page', 1 , type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=6)
    return render_template('community.html', title='Community', posts=posts)

election/posts/routes.py
from flask import Blueprint, render_template, url_for, flash , redirect, request , abort
from flask_login import current_user , login_required
from election import db
from election.models import Post
from election.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

election/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from election import db, bcrypt
from election.models import User, Post
from election.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from election.users.util import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

election/templates/about.html
{% extends "layout.html" %}

{% block content %}

  <h1> THIS IS AN ELECTION WEBSITE </h1>


{% endblock  %}

election/templates/account.html
{% extends "layout.html" %}
{% block content %}
        <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{image_file}}">
        <div class="media-body">
          <h2 class="account-heading">{{current_user.username}}</h2>
          <p class="text-secondary">{{current_user.email }}</p>
        </div>
        </div>
        <!-- FORM HERE -->

            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info </legend>
                    <!-- This is where the username is entered -->
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                    <!-- This is where the email is entered  -->
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}

                            {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span>
                            {% endfor %}

                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>


{% endblock  %}

election/templates/community.html
{%extends "layout.html"%}

{% block content %}
    {% for post in posts.items %}

            <article class="media content-section">
            <img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d')}}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
        </article>

    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

        {% if page_num %}
            {%if posts.page==page_num %}
                <a class = "btn btn-info mb-4" href="{{ url_for('main.home',page=page_num)}}"> {{page_num}} </a>
            {%else %}
                <a class = "btn btn-outline-info mb-4" href="{{ url_for('main.home',page=page_num)}}"> {{page_num}} </a>
            {%endif%}
        {% else %}
            ...

        {%endif%}

    {%endfor%}


{% endblock %}

election/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock  %}

election/templates/home.html
{% extends "layout.html" %}



{% block content %}
<script>
        // Set the date we're counting down to
        var countDownDate = new Date("Nov 3, 2020 00:00:01").getTime();

        // Update the count down every 1 second
        var x = setInterval(function() {

          // Get today's date and time
          var now = new Date().getTime();

          // Find the distance between now and the count down date
          var distance = countDownDate - now;

          // Time calculations for days, hours, minutes and seconds
          var days = Math.floor(distance / (1000 * 60 * 60 * 24));


          // Display the result in the element with id="demo"
          document.getElementById("demo").innerHTML = days
          // If the count down is finished, write some text
          if (distance < 0) {
            clearInterval(x);
            document.getElementById("demo").innerHTML = "EXPIRED";
          }
        }, 1000);

</script>

    <main role="main" class="container">
    <main class="css-17j3c3d">
    <div class="row">
    <div class="col-md-8">
    <div class="css-zwkg4z">
    <div class=".css-89xpxa">


    <section style="position:relative">

    <!-- Top Story Header -->
    <header>
    <div class="css-18wsigh">
    <span class="css-x5e31x">
    <span class="css-1jr5l57"><b> News </b> </span> "Top Story" </span>
    </div>
    <br>
    </header>


    <!-- Top Story Picture -->
    <article>
    <a href="/not_done">
    <div>
    <img title="SC Top Story" width="90%" src="{{url_for('static', filename='debate_Cunningham.png')}}">
    </img>
    </div>

    <!-- Top Story Description -->
    <h2 class="css-rlawu">
    In final SC congressional debate, Nancy Mace and Joe Cunningham try to avoid Trump
    </h2>
    <div>
    <span class="css-o3ula8 e13bwyn60">
    By
    <!-- -->
    Sean Williams
    </span>
    </div>
    </a>
    </article>






    </section>
    </div>
    </div>
    </div>



    <div class="col-md-4" style="position:relative">
    <section>



    <!-- Other Articles Header -->
    <header>
    <span class="css-x5e31x">
    <span class="css-1jr5l57"> <b> News </b>  </span> "Featured" </span>
    </header>



    <!-- Other Articles -->
    <div class="css-z78f2p">


    <article class="css-1tdvlph">

    <a class="css-k008qs" href="/not_done">
    <div class="css-1ev106r">
    <div class="css-8atqhb">
    <img title="Another Story" width="100%" src="{{url_for('static', filename='CunninghamStory.jpg')}}">
    </div>
    </div>

    <div class="css-hoe9xz">


      <h3 style="color:#0D0D0D;margin-top:0" class="css-1628fxq e7f1hlv0">
      Environmental laws passed by Cunningham
      </h3>

    <div class="css-94x4tq e13bwyn60">
    By <!-- --> Keelin White
    </div>

    </div>
    </a>

    </article>

    <article class="css-1tdvlph">
      <a class="css-k008qs" href="/not_done">
      <div class="css-1ev106r">
      <div class="css-8atqhb">
      <img title="Another Story" width="100%" src="{{url_for('static', filename='Lindsey_Graham.jpg')}}">
      </div>
      </div>

      <div class="css-hoe9xz">


        <h3 style="color:#0D0D0D;margin-top:0" class="css-1628fxq e7f1hlv0">
        Will the silent majority show up for Graham?
        </h3>

      <div class="css-94x4tq e13bwyn60">
      By <!-- --> Sandra Black
      </div>

      </div>
      </a>

    </article>

    <article class="css-1tdvlph">
      <a class="css-k008qs" href="/not_done">
      <div class="css-1ev106r">
      <div class="css-8atqhb">
      <img title="Another Story" width="100%" src="{{url_for('static', filename='Scott.jpeg')}}">
      </div>
      </div>

      <div class="css-hoe9xz">


        <h3 style="color:#0D0D0D;margin-top:0" class="css-1628fxq e7f1hlv0">
        Is Tim Scott the future of the GOP?
        </h3>

      <div class="css-94x4tq e13bwyn60">
      By <!-- -->Joseph Curl
      </div>

      </div>
      </a>

    </article>


    </section>
    </div>



    </div>

    </main>
    </main>

    <div class="Toastify"><br><br></div>
    <div class="css-d7h9ck">
      <section id="election-signup" class="css-dhro7d e1kbyuqk0" width="100%">
        <h1 class="css-5w0168 e1kbyuqk1">
          <br>
          <span class="css-3ulb31 e17f3ixj1" id="demo">
          </span>

          <span class="css-1cbifvp e1kbyuqk2"> days <!-- -->until election</span>
        </h1>

        <div class="css-0 e1kbyuqk3">
        <h2 class="css-12xet20 e1kbyuqk4">Don't miss out on our coverage.</h2>
        <br> <br><br><br>
        </div>
    </div>



{% endblock %}

election/templates/layout.html
<!DOCTYPE html>
<html>
<head>


     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">


    {% if title %}
        <title> Election 2020 - {{title}} </title>
    {% else %}
        <title> SC Election 2020 </title>
    {% endif %}

</head>
<body>
    <header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top css-dhro7d-w navpad">
    <div class="container" id="div.container">
      <a class="navbar-brand mr-4 home_title" href="/">
      2020 SC Election
      </a>

      <div class="collapse navbar-collapse css-h6is44" id="navbarToggle">
        <div class="navbar-nav mr-auto dropdown">
          <a class="nav-item nav-link css-193va6t1" href="{{ url_for('main.not_done')}}">Polls</a>
          <a class="nav-item nav-link css-193va6t1" href="{{ url_for('main.not_done')}}">Candidates</a>
            <a class="nav-item nav-link css-193va6t2" href="{{ url_for('main.community')}}">Community</a>
        </div>


        <!-- Navbar Right Side -->
        <div class="navbar-nav" whitespace="no-wrap">
            {%if current_user.is_authenticated %}
                <a class="nav-item nav-link css-193va6t3" href="{{ url_for('posts.new_post')}}">New Post</a>
                <a class="nav-item nav-link css-193va6t1" href="{{ url_for('users.user_posts',username=current_user.username)}}">Your Posts</a>
                <a class="nav-item nav-link css-193va6t1" href="{{ url_for('users.account')}}">Settings</a>
                <a class="nav-item nav-link css-193va6t1" href="{{ url_for('users.logout')}}">Logout</a>


            {% else %}
                <a class="nav-item nav-link css-193va6t1" href="{{ url_for('users.login')}}">Login</a>
                <a class="nav-item nav-link css-193va6t1" href="{{ url_for('users.register')}}">Register</a>
            {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>


  {% block content %}
  {% endblock %}





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

election/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                    <small class="text-muted ml-2">
                      <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    </small>
            </div>

        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock %}

election/templates/not_done.html
{% extends "layout.html" %}

{% block content %}

  <h1 align="middle"> Page under construction </h1>


{% endblock  %}

election/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{url_for('posts.user_post',username=post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d')}}</small>
            {% if post.author ==current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm m-1" href="{{url_for('posts.update_post',post_id=post.id)}}"> Update </a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal"> Delete </button>
                </div>
            {%endif%}
    </div>
        <h2 class="article-title"><{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>

</article>




<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{url_for('posts.delete_post', post_id=post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="YES">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

election/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}


                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit() }}
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>

    </div>

{% endblock %}

election/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
{%if current_user.username == user.username%}
  <h1 class="mb-3" align="center"> Your Posts - {{posts.total}} total </h1>
{%else%}
    <h1 class="mb-3"> Posts by {{user.username}} ({{posts.total}}) </h1>
{%endif%}
    {% for post in posts.items %}
            <article class="media content-section">
            <img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}"> {{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d')}}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
        </article>

    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

        {% if page_num %}
            {%if posts.page==page_num %}
                <a class = "btn btn-info mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num)}}"> {{page_num}} </a>
            {%else %}
                <a class = "btn btn-outline-info mb-4" href="{{ url_for('users.user_posts',username=user.username,page=page_num)}}"> {{page_num}} </a>
            {%endif%}
        {% else %}
            ...

        {%endif%}

    {%endfor%}


{% endblock %}